# https://github.com/Homebrew/homebrew-core/blob/4dd41236ab23102e91457f9f48962dbe93232f86/Formula/aws-sdk-cpp.rb

distributable:
  url: https://github.com/aws/aws-sdk-cpp/archive/refs/tags/{{version}}.tar.gz

# https://github.com/aws/aws-sdk-cpp/blob/main/.gitmodules
# https://github.com/aws/aws-sdk-cpp/tree/main/crt
# https://github.com/awslabs/aws-crt-cpp/blob/cb474daeeaf5c025bd3408103adf61b97b74e600/.gitmodules

versions:
  github: aws/aws-sdk-cpp/tags

# provides:
#   - bin/aomenc
#   - bin/aomdec

dependencies:
  curl.se: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    cmake.org: '*'
    tea.xyz/gx/make: '*'
  working-directory: aws-sdk-cpp-{{version}}
  script: |
    # ENV.append "LDFLAGS -Wl,-rpath,#{rpath}
    # Avoid OOM failure on Github runner
    # ENV.deparallelize if OS.linux? && ENV["HOMEBREW_GITHUB_ACTIONS"]

    rm -rf crt/aws-crt-cpp
    git clone --recurse-submodules https://github.com/awslabs/aws-crt-cpp.git crt/aws-crt-cpp

    # git submodule update --init --recursive

    cmake -S . -B build $ARGS
    cmake --build build
    cmake --install build

    # lib.install Dir[lib/"mac/Release/*"].select { |f| File.file? f }
  env:
    LDFLAGS: -Wl,-rpath,{{prefix}}
    ARGS:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DENABLE_TESTING=OFF

test:
  fixture: |
    #include <aws/core/Version.h>
    #include <iostream>

    int main() {
      std::cout << Aws::Version::GetVersionString() << std::endl;
      return 0;
    }
  script: |
    mv $FIXTURE test.cpp
    c++ -std=c++11 test.cpp -laws-cpp-sdk-core -o test
    ./test
