distributable:
   url: https://github.com/facebook/wangle/archive/refs/tags/v{{version.raw}}.tar.gz
   strip-components: 1

versions:
  github: facebook/wangle
  strip: /v/

dependencies:
  boost.org: '*'
  google.com/double-conversion: ^3
  github.com/facebookincubator/fizz: '*'
  fmt.dev: ^9
  facebook.com/folly: '*'
  gflags.github.io: '*'
  google.com/glog: '*'
  libevent.org: '*'
  libsodium.org: '*'
  lz4.org: ^1
  openssl.org: ^1.1
  google.github.io/snappy: '*'
  facebook.com/zstd: ^1
  darwin:
    sourceware.org/bzip2: '*'
    zlib.net: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    cmake.org: ^3
  working-directory: wangle
  script: |
    cmake . -DBUILD_SHARED_LIBS=ON $ARGS
    make install

    make clean

    cmake . -DBUILD_SHARED_LIBS=OFF $ARGS
    make

    sed -i.bak "s:$(tea --prefix):\$\{_IMPORT_PREFIX\}/../../../..:g" "{{prefix}}"/lib/cmake/wangle/wangle-targets.cmake
    rm "{{prefix}}"/lib/cmake/wangle/wangle-targets.cmake.bak
  env:
    ARGS:
      - -DCMAKE_INSTALL_PREFIX={{prefix}}
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF

test:
  dependencies:
    tea.xyz/gx/cc: c99
  script: |
    c++ $CXXFLAGS 'EchoClient.cpp' -o EchoClient
    c++ $CXXFLAGS 'EchoServer.cpp' -o EchoServer

    # Find a free port
    FREE_PORT=0
    while :; do
        FREE_PORT=$(shuf -i 49152-65535 -n 1)
        if ! (nc -z 127.0.0.1 ${FREE_PORT}) 2>/dev/null; then
            break
        fi
    done

    # Start the EchoServer
    ./EchoServer -port "${FREE_PORT}" &
    SERVER_PID=$!
    sleep 10

    # Run the EchoClient and interact with the EchoServer
    OUTPUT_FILE=output.txt
    rm -f "${OUTPUT_FILE}"
    mkfifo "${OUTPUT_FILE}"
    cat > "${OUTPUT_FILE}" &
    CLIENT_BACKGROUND_PID=$!

    # Send test lines to the EchoClient
    ./EchoClient -port "${FREE_PORT}" > "${OUTPUT_FILE}" << EOF
    Hello from tea!
    Another test line.
    EOF

    sleep 20

    # Kill the EchoServer and EchoClient
    kill "${SERVER_PID}"
    kill "${CLIENT_BACKGROUND_PID}"

    # Check the output for the test lines
    grep -q "Hello from Homebrew!" "${OUTPUT_FILE}"
    grep -q "Another test line." "${OUTPUT_FILE}"

    # Cleanup
    rm -f "${OUTPUT_FILE}"
  env:
    CXXFLAGS:
      - -std=c++17
      - -lgflags
      - -lglog
      - -lfolly
      - -lfizz
      - -lwangle
    linux:
      CXXFLAGS:
       - -lboost_context-mt
       - -ldl
       - -lpthread
